apiVersion: v1
kind: Pod
metadata:
  name: fortune-https
spec:
  imagePullSecrets:
  - name: docker-secret
  containers:
  - image: vlaviar/fortune:args
    name: html-generator
    env:
    - name: INTELRVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config-2
          key: sleep-interval
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config-files
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
      readOnly: true
    - name: certs
      mountPath: /etc/nginx/certs
      readOnly: true
    ports:
    - containerPort: 80
    - containerPort: 443
  volumes:
  - name: html
    emptyDir:
      medium: Memory
  - name: config-files
    configMap:
      name: fortune-config-2
      items:
      - key: my-nginx-config.conf
        path: default.conf
  - name: certs
    secret:
      secretName: fortune-https
