apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: vlaviar-ingress-2
spec:
  rules:
  - host: vlaviar-kubia-2.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vlaviar-loadbalancer-svc
            port:
              number: 80
