apiVersion: batch/v1
kind: Job
metadata:
  name: VlaViar
spec:
  completions: 5
  parallelism: 3
  template:
    metadata:
      labels:
        app: job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: job
        image: luksa/batch-job
