apiVersion: v1
kind: Service
metadata:
  name: kubia-2-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: kubia2
