apiVersion: v1
kind: Pod
metadata:
  name: pod-git-nginx
  labels:
    app: nginx
spec:
  containers:
  - image: vlaviar/nginx-and-git:latest
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/VlaViar/Nginx-files.git
      revision: master
      directory: .
