apiVersion: v1
kind: Pod
metadata:
  name: pod-git-nginx
spec:
  volumes:
  - name: html
    emptyDir: {}

  initContainers:
  - name: git-clone
    image: alpine/git
    command:
      - sh
      - -c
      - git clone --branch master https://github.com/VlaViar/Nginx-files.git /html
    volumeMounts:
    - name: html
      mountPath: /html

  containers:
  - name: web-server
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80

  - name: git-sync
    image: registry.k8s.io/git-sync/git-sync:v4.0.0
    env:
    - name: GIT_SYNC_REPO
      value: "https://github.com/VlaViar/Nginx-files.git"
    - name: GIT_SYNC_BRANCH
      value: "master"
    - name: GIT_SYNC_ROOT
      value: "/git"
    - name: GIT_SYNC_DEST
      value: "html"
    - name: GIT_SYNC_ONE_TIME
      value: "false"
    volumeMounts:
    - name: html
      mountPath: /git/html

