apiVersion: v1
kind: Pod
metadata:
  name: pod-git-nginx
spec:
  containers:
    - name: git-sync
      image: registry.k8s.io/git-sync/git-sync:v4.0.0
      securityContext:
        runAsUser: 0
      env:
        - name: GITSYNC_REPO
          value: https://github.com/VlaViar/Nginx-files.git
        - name: GITSYNC_BRANCH
          value: master
        - name: GITSYNC_ROOT
          value: /git
        - name: GITSYNC_DEST
          value: .
        - name: GITSYNC_ONE_TIME
          value: "false"
        - name: GITSYNC_WAIT
          value: "10"
      volumeMounts:
        - name: html
          mountPath: /git

    - name: web-server
      image: nginx
      securityContext:
        runAsUser: 1000  # Используем стандартного пользователя nginx, например, 1000
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html
      emptyDir: {}  # Или PersistentVolume, если хочешь сохранять данные
