apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test
    env: default
spec:
  containers:
  - name: kubia-test
    image: luksa/kubia
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
