apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  labels:
    app: test-kubia
    env: default
spec:
  containers:
  - name: kubia-test
    image: luksa/kubia
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    - name: https
      containerPort: 8443
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 3
      timeoutSeconds: 1
